chore(bigcommerce): Update development requirements
CI / check migrations with `bigcommerce` package missing.

Error: ModuleNotFoundError: No module named 'bigcommerce'