feat(config): Remove deprecated Badges courseware tab from hawthorn release.
Removed hawthorn way of displaying Badges frontend since maple uses the mfe frontend when viewing the courseware. Hawthorn had included a <iframe /> to the mfe frontend but kept the courseware navigation wrapper in the platform codebase.

Received the following LMS error when using `hawthorn` based data from MongoDB. It looks like we had previously had the courseware tab with name `course_badges` and these was being stored the MongoDB database with this value so courses that initially had badges setup through this error.

LMS Error:
edx_django_utils.plugins.plugin_manager.PluginError: No such plugin course_badges for entry point openedx.course_tab